pipeline:
  dependencies:
    image: node:dubnium
    commands:
      - ./scripts/check-lockfile.sh

  deploy-twigjs-preview:
    group: previews
    image: node:dubnium
    secrets: [gh_token]
    commands:
      - yarn clean
      - yarn dist
    when:
      event: push
      status: [success, failure]
      branch:
        exclude:
          - master

  deploy-twigphp-preview:
    group: previews
    image: roelofr/php-node
    secrets: [gh_token]
    commands:
      - npm install -g n && n stable
      - yarn install
      - rm -rf netlify.toml
      - yarn setupPhp
      - yarn dist:php
      - yarn diff
    environment:
      - DEPLOY_CONTEXT=preview/twig-php
    when:
      event: push
      status: [success, failure]
      branch:
        exclude:
          - master
