pipeline:
  dependencies:
    image: node:dubnium
    commands:
      - ./scripts/check-lockfile.sh

  lint:
    group: tests
    image: node:dubnium
    commands:
      - yarn lint && yarn pretty:check

  jest:
    group: tests
    image: node:dubnium
    commands:
      - yarn jest

  check-build:
    image: node:dubnium
    secrets: [gh_token]
    commands: node scripts/failcheck.js

  deploy-twigjs-preview:
    group: previews
    image: node:dubnium
    secrets: [gh_token]
    commands:
      - yarn dist
    when:
      event:
        - push
        - pull_request
      branch:
        exclude:
          - master

  deploy-twigphp-preview:
    group: previews
    image: roelofr/php-node
    secrets: [gh_token]
    commands:
      - npm install -g n && n stable
      - yarn install
      - rm -rf netlify.toml
      - yarn php:install
      - yarn php:dist
      - yarn diff
    environment:
      - DEPLOY_CONTEXT=preview/twig-php
    when:
      event:
        - push
        - pull_request
      status: [success, failure]
      branch:
        exclude:
          - master
